import express from "express";
import {config} from "dotenv";
import cors from "cors";
import router from "./router.js";
config({path:"./config.env"});
export const app=express();
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({extended:true}));
app.use("/api",router);
app.get("/api/getkey",(req,res)=>{res.status(200).json({key:process.env.RAZORPAY_KEY})});